- hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: Copying yaml
    copy:
      src: ./jenk_kube.yml
      dest: /tmp/jenk_kube.yml
  - name: Deployment
    become_user: femsk
    shell: |
      kubectl apply -f /tmp/jenk_kube.yml -n diploma