- hosts: worker1
  become: yes
  gather_facts: false
  tasks:
  - name: Copying yaml
    copy:
      src: ./jenk.yml
      dest: /tmp/jenk.yml
  - name: Deployment
    become_user: femsk
    shell: |
      kubectl apply -f /tmp/jenk.yml -n diploma