apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kube
  namespace: diploma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-kube
  template:
    metadata:
      labels:
        app: jenkins-kube
    spec:
      containers:
      - name: jenkins-kube
        image: femsk/diploma:1.0
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
      volumes:
        - name: jenkins-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-kube
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins-kube
  externalIPs:
    - 158.160.111.8
