#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-jenk
#  namespace: diploma
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/var/k8s/mnt"
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jenkvol
#  namespace: diploma
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 300Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      run: jenk-app
  replicas: 1
  template:
    metadata:
      labels:
        run: jenk-app
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
    spec:
      containers:
        - name: jenkins
          image: femsk/diploma:1.1
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 50000
              name: jnlp
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: pv-jenk
      volumes:
        - name: pv-jenk
          persistentVolumeClaim:
            claimName: jenkvol
---
apiVersion: v1
kind: Service
metadata:
  name: serv-jenk
  namespace: diploma
  labels:
      app: jenk-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  externalIPs:
      - 158.160.111.8
---
apiVersion: v1
kind: Service
metadata:
  name: serv-jenk-jnlp
  namespace: diploma
  labels:
      app: jenk-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000

#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: serv-jenk
#subsets:
#  - addresses:
#      - ip: 10.244.2.37
#    ports:
#      - port: 8080