- hosts: master
  become: yes
  tasks:
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: diploma
      api_version: v1
      kind: Namespace
      state: present

  - name: Create a Deployment
    gather_facts: false
    kubernetes.core.k8s:
      namespace: diploma
      state: present
      src: nginx.yml