apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
        - name: nginx
          image: femsk/nginx:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: serv-nginx
spec:
  type: NodePort
  selector:
    run: ng-app
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
  externalIPs:
      - 158.160.98.13

