apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
        - name: nginx
          image: femsk/nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  name: serv-nginx
  namespace: diploma
  labels:
      app: ng-app
spec:
  type: LoadBalancer
#  selector:
#    run: ng-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  externalIPs:
      - 158.160.98.13

---
kind: Endpoints
apiVersion: v1
metadata:
  name: serv-nginx
subsets:
  - addresses:
      - ip: 10.244.2.2
      - ip: 10.244.1.2
    ports:
      - port: 80

