apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: diploma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: femsk/nginx:1.0.${BUILD_NUMBER}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx
  externalIPs:
    - 158.160.111.8


