- hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: Deployment
    become_user: femsk
    shell: |
      git clone --recurse-submodules https://github.com/fermsk/diploma.git
      cd diploma/kube-prometheus
      kubectl create -f manifests/setup
      kubectl create -f manifests
      kubectl apply -f ../monitor/grafana-service.yaml
      rm -rf ../../diploma